apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rebootpod-controller
  name: {{ include "chart.fullname" . }}-rebootpod-editor-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - gauravkr19.dev
  resources:
  - rebootpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gauravkr19.dev
  resources:
  - rebootpods/status
  verbs:
  - get
