//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootPod) DeepCopyInto(out *RebootPod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootPod.
func (in *RebootPod) DeepCopy() *RebootPod {
	if in == nil {
		return nil
	}
	out := new(RebootPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RebootPod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootPodList) DeepCopyInto(out *RebootPodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RebootPod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootPodList.
func (in *RebootPodList) DeepCopy() *RebootPodList {
	if in == nil {
		return nil
	}
	out := new(RebootPodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RebootPodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootPodSpec) DeepCopyInto(out *RebootPodSpec) {
	*out = *in
	if in.RestartTargets != nil {
		in, out := &in.RestartTargets, &out.RestartTargets
		*out = make([]RestartTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootPodSpec.
func (in *RebootPodSpec) DeepCopy() *RebootPodSpec {
	if in == nil {
		return nil
	}
	out := new(RebootPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootPodStatus) DeepCopyInto(out *RebootPodStatus) {
	*out = *in
	in.RolloutStatus.DeepCopyInto(&out.RolloutStatus)
	in.RebootCompleted.DeepCopyInto(&out.RebootCompleted)
	in.LastHealthCheck.DeepCopyInto(&out.LastHealthCheck)
	in.VaultSyncStatus.DeepCopyInto(&out.VaultSyncStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootPodStatus.
func (in *RebootPodStatus) DeepCopy() *RebootPodStatus {
	if in == nil {
		return nil
	}
	out := new(RebootPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootState) DeepCopyInto(out *RebootState) {
	*out = *in
	if in.FailedHealthChecks != nil {
		in, out := &in.FailedHealthChecks, &out.FailedHealthChecks
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootState.
func (in *RebootState) DeepCopy() *RebootState {
	if in == nil {
		return nil
	}
	out := new(RebootState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartTarget) DeepCopyInto(out *RestartTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartTarget.
func (in *RestartTarget) DeepCopy() *RestartTarget {
	if in == nil {
		return nil
	}
	out := new(RestartTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.FailedResources != nil {
		in, out := &in.FailedResources, &out.FailedResources
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSync) DeepCopyInto(out *VaultSync) {
	*out = *in
	if in.SynchedSecret != nil {
		in, out := &in.SynchedSecret, &out.SynchedSecret
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSync.
func (in *VaultSync) DeepCopy() *VaultSync {
	if in == nil {
		return nil
	}
	out := new(VaultSync)
	in.DeepCopyInto(out)
	return out
}
