apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rebootpod-controller
  name: {{ include "chart.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}

