apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rebootpod-controller
    control-plane: controller-manager
  name: {{ include "chart.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: metrics
    port: 8082
    protocol: TCP
    targetPort: 8082    
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP

